// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njdyjtpkaqizajugpetc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZHlqdHBrYXFpemFqdWdwZXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjAzMjIsImV4cCI6MjA3MDI5NjMyMn0.QemyZGXbwUmkSigjkY87Gc8HYj8ukiwMMPcCQQFnAfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});